### ISSUE TITLE
dnsRecords.add() adds a record, even if an existing record with the same name is already present

### ISSUE THREAD

**Issue by jay-dee7** [cloudflare/node-cloudflare#46]
## Expected behavior
return an error saying record already exists with the same name

## Actual Behavior
add the record anyway

**Comment by terinjokes** [comment]
This doesn't seem like a bug in the API bindings.

The same name appearing in DNS multiple times is valid. This often regularly happens when adding A and AAAA records for IPv4 and IPv6 sites. It's even valid within the same type, when configuring a domain for email, multiple MX records of the same name will be added with different values.

The API, or the API bindings, preventing users from duplicating names would prevent these valid use cases from working.
